x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor #локальный запуск
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    AIRFLOW__WEBSERVER__SECRET_KEY: 'your_airflow_webserver_sec_key'
    _PIP_ADDITIONAL_REQUIREMENTS: ''
    AIRFLOW_INPUT_DIR: '/opt/airflow/dag-inputs'
    AIRFLOW_CONN_WRITE_TO_POSTGRES: 'postgresql://airflow:airflow@postgres:5432/sample'
    AIRFLOW_CONN_WRITE_TO_POSTGRES_TELEMETRY: 'postgresql://telemetry_user:telemetry_password@telemetry_db:5432/telemetry_db'
    AIRFLOW_CONN_WRITE_TO_POSTGRES_CRM: 'postgresql://crm_user:crm_password@crm_db:5432/crm_db'
    AIRFLOW_CONN_WRITE_TO_CLICKHOUSE: 'clickhouse://airflow:airflow@clickhouse:8123/olap'

  volumes:
    - ./dags:/opt/airflow/dags
    - ./dags/sql:/opt/airflow/dags/sql
    - ./requirements.txt:/opt/airflow/requirements.txt
    - ./data:/opt/airflow/sample_files
  depends_on: &airflow-common-depends-on
    postgres:
      condition: service_healthy
  networks:
    - dag_sample

services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - dag_sample

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
    networks:
      - dag_sample

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_KEYCLOAK_URL: http://localhost:8080
      REACT_APP_KEYCLOAK_REALM: reports-realm
      REACT_APP_KEYCLOAK_CLIENT_ID: reports-frontend
    networks:
      - dag_sample

  postgres:
    image: postgres:14
    volumes:
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - airflow
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - dag_sample

  airflow-webserver:
    <<: *airflow-common

    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    command: webserver
    networks:
      - dag_sample
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  airflow-scheduler:
    <<: *airflow-common
    networks:
      - dag_sample
    command: scheduler
    depends_on:
      telemetry_db:
        condition: service_healthy
      crm_db:
        condition: service_healthy
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      airflow-webserver:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  airflow-triggerer:
    <<: *airflow-common
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    networks:
      - dag_sample
    command: bash -c "airflow triggerer"
    healthcheck:
      test:
        - CMD-SHELL
        - airflow jobs check --job-type TriggererJob --hostname "${HOSTNAME}"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  airflow-cli:
    <<: *airflow-common
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dag_sample
    profiles:
      - debug
    command:
      - bash
      - -c
      - airflow

  airflow-init:
    <<: *airflow-common
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "airflow db init && airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@sample.ru --password admin"
    networks:
      - dag_sample

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: bionicpro-olap
    environment:
      CLICKHOUSE_USER: airflow
      CLICKHOUSE_PASSWORD: airflow
      CLICKHOUSE_DB: olap
    ports:
      - "8123:8123"
      - "9431:9000"
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse
      - ./clickhouse/init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./clickhouse/init/data.csv:/tmp/data.csv
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query 'SELECT 1'"]
      interval: 1s
      timeout: 3s
      retries: 30
    restart: always
    networks:
      - dag_sample

  telemetry_db:
    image: postgres:14
    container_name: bionicpro-telemetry-postgres
    environment:
      POSTGRES_DB: telemetry_db
      POSTGRES_USER: telemetry_user
      POSTGRES_PASSWORD: telemetry_password
    volumes:
      - ./telemetry/init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./telemetry/init/data.csv:/tmp/data.csv
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U telemetry_user -d telemetry_db"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always
    networks:
      - dag_sample

  crm_db:
    image: postgres:14
    container_name: bionicpro-crm-postgres
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
    volumes:
      - ./crm/init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./crm/init/data.csv:/tmp/data.csv
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crm_user -d crm_db"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always
    networks:
      - dag_sample

  backend:
    container_name: bionicpro-report-service
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_DATABASE: olap
      CLICKHOUSE_USERNAME: airflow
      CLICKHOUSE_PASSWORD: airflow
      REPORTS_TABLE: bionicpro_analytics
#      KEYCLOAK_JWKS_URL: http://host.docker.internal:8080/realms/reports-realm/protocol/openid-connect/certs
#      KEYCLOAK_EXPECTED_ISSUER: http://localhost:8080/realms/reports-realm
#      ALLOWED_ORIGINS: http://localhost:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    depends_on:
      clickhouse:
        condition: service_healthy
#      keycloak:
#        condition: service_started
    networks:
      - dag_sample


networks:
  dag_sample:
